### ISSUE TITLE
Issue pushing bullet

### ISSUE THREAD

**Issue by atomi** [jaxbot/irssi-pushbullet-notifications#4]
Since yesterday I've been getting these errors:

`Issue pushing bullet`

This is likely an issue at Pushbullet but I'm unfamiliar with debugging Irssi plugins to confirm.

**Comment by atomi** [comment]
`$retcode` returned `35` some type of ssl error, the image I'm using was missing `ca-certificates` so I added those via `apt-get`.  I hope that's it. But I'll re-open and troubleshoot more if the issue persists. Thanks for this, it's super helpful.

**Comment by atomi** [comment]
More info:

```
                * Connection 3 seems to be dead!
* Closing connection 3
* Hostname was NOT found in DNS cache
*   Trying 72.14.247.65...
* Connected to api.pushbullet.com (72.14.247.65) port 443 (#4)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* SSL re-using session ID
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 4
* Hostname was found in DNS cache
*   Trying 72.14.247.65...
* Connected to api.pushbullet.com (72.14.247.65) port 443 (#5)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* SSL re-using session ID
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 5
```

**Comment by atomi** [comment]
Still happening :(

**Comment by nothingmuch** [comment]
Hmm, I was thinking of switching this over to LWP::UserAgent since it simplifies the code a bit IMHO, but it might help with the SSL stuff if it pushes SSL handling to some other stack (though TBH I don't really know how either handles SSL and I suspect they will both rely on the same underlying impl eventually)

I'll give it a shot later tonight

**Comment by atomi** [comment]
:+1:  Thanks!!

**Comment by atomi** [comment]
I think this might be an issue with my setup which is Docker on RaspberryPi. Added `--net host` and it seems to be pushing consistently. Likely a network issue with Docker arm build...

**Comment by atomi** [comment]
Still happening :(

**Comment by atomi** [comment]
FYI: I narrowed this issue down to the libwww-curl-perl package in Raspbian Jessie.

https://bugs.launchpad.net/raspbian/+bug/1486110
